### ISSUE TITLE
Missing sound files

### ISSUE THREAD

**Issue by bentley** [DusteDdk/Wizznic#14]
I get this error whenever I try to run wizznic (empty ~/.wizznic):

    $ wizznic        
    Wizznic 1.0-dev. GPLv3 or newer Copyleft 2009-2015
    
    Directories:
        Settings: /home/anthony/.wizznic
        DLC: /home/anthony/.wizznic/dlc
        Highscores: /home/anthony/.wizznic/highscores
        Editorlevels: /home/anthony/.wizznic/editorlevels
        Datafiles: /usr/local/share/wizznic/
    
    Command-line parameters:
        -gl            # Enable OpenGL.
        -sw            # Disable OpenGL.
        -glheight PX   # Window width  (-1 for auto).
        -glwidth  PY   # Window height (-1 for auto).
        -glfilter ST   # 0=Blocky, 1=Smooth.
        -rift          # Usable for Oculus Rift.
        -record [file] # on pc, use ffmpeg to encode video to file.mp4
        -d PACKNAME    # Dump screenshots of levels in pack.
        -d FILENAME    # Dump screenshot of level.
        -f             # Enable fullscreen.
        -w             # Disable fullscreen.
        -z 2           # Software scale to 640x480.
    Loading settings from: /home/anthony/.wizznic/settings.ini
    Enabling platform specific accelerated scaling.
    Scaling factor: 5.000000
    Screen surface using 3 bytes per pixel.
    statsInit(); Stats ready to be refreshed.
    initPack();
    initPack(); Added 12 packs.
    Applying settings..
    packSet(); Selecting pack 0...
    packSet(); Selected pack '/usr/local/share/wizznic/packs/000_wizznic' Loading stats..
    packSet(); Stats loaded.
    Setting Music...
    loadSample(); Warning: Couldn't load /usr/local/share/wizznic/packs/000_wizznic/themes/oldskool/snd/brickswap.ogg
    loadSample(); Warning: Couldn't load /usr/local/share/wizznic/packs/000_wizznic/themes/oldskool/snd/brickcopy.ogg
    loadSample(); Warning: Couldn't load /usr/local/share/wizznic/packs/000_wizznic/themes/oldskool/snd/brickswapdenied.ogg
    loadSample(); Warning: Couldn't load /usr/local/share/wizznic/packs/000_wizznic/themes/oldskool/snd/brickcopydenied.ogg
    Bus error (core dumped)

**Comment by DusteDdk** [comment]
Hi Anthony,

That's pretty weird.
The missing soundfiles are not the cause of this issue, they've not been created, so that's a normal message.
I'm uncertain why it dumps. I might be able to pinpoint it if I get more information.

Operating system
CPU architecture
Screen resolution and bit-depth
Graphcis card and driver
Number of screens
Did you compile it yourself, if so, from which version of the source code, using which command ?
If you didn't compile it yourself, how did you install it?

My first, naieve idea, is that MAYBE you're runnign a huge resolution on a graphics card which won't allow to allocate a texture that fits (and is still a power of two).
You might experiment with turning opengl on and off.
Try without opengl:
./wizznic -sw -w
If that works, try
./wizznic -sw -w -z 2
If that works, try
./wizznic -sw -w -z 4
And, if that works, try
./wizznic -sw -f -z 4
That should give you full-screen, software mode.

If you have trouble with those, try
./wizznic -gl -w -glwidth 640 -glheight 480
And so on.

Hope to hear from you, also if you get it working, I'd like to know how :)
Best Regards
 Jimmy Christensen
